# note the binary is built and deployed using jenkins

- name: Install polkit
  ansible.builtin.apt:
    pkg:
      - polkitd
  become: true
- name: Install polkit rule
  ansible.builtin.template:
    src: templates/10-stream-controller.rules.j2
    dest: /etc/polkit-1/rules.d/10-stream-controller.rules
    owner: root
    group: root
    mode: 0644
  become: true

- name: Install systemd service
  ansible.builtin.template:
    src: templates/stream-controller.service.j2
    dest: /etc/systemd/system/stream-controller.service
    owner: root
    group: root
    mode: 0644
  become: true
- name: Enable and start systemd service
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: stream-controller.service
    daemon_reload: true
  become: true
