- name: Install nginx
  ansible.builtin.apt:
    pkg:
      - nginx
  become: true

- name: Create hls directory
  ansible.builtin.file:
    state: directory
    path: '/var/www/hls/'
    owner: streaming
    mode: 0755
  become: true

- name: Install nginx configuration (stream.radio.roses.media)
  ansible.builtin.template:
    src: templates/stream.radio.roses.media.conf
    dest: /etc/nginx/sites-enabled/stream.radio.roses.media.conf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Remove nginx default configuration
  ansible.builtin.file:
    state: absent
    path: /etc/nginx/sites-enabled/default
  become: true

- name: Reload nginx
  ansible.builtin.systemd_service:
    state: reloaded
    enabled: true
    name: nginx.service
  become: true
