on:
  push:
    branches: [main]
    paths:
      - stream-controller/**/*
      - .github/workflows/build-stream-controller.yml

jobs:
  build-stream-controller:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: target/**
          key: cargo
      - name: Install rust toolchain
        run: rustup update stable && rustup default stable
      - name: Build with cargo
        run: cargo build --verbose --release
        working-directory: stream-controller/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stream-controller
          path: stream-controller/target/release/stream-controller
